active: "testnet"

prod:
  node: 
    gaiad_url: "http://13.209.59.177:26657"
    lcd_url: "https://lcd.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "mainnet"

dev:
  node: 
    gaiad_url: "tcp://52.78.163.36:26657"
    lcd_url: "https://lcd-mainnet-dev.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "dev-test"

testnet:
  node: 
    gaiad_url: "tcp://54.180.171.141:26657"
    lcd_url: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"

keybase_url: "https://keybase.io/_/api/1.0/user/lookup.json?fields=pictures&key_suffix="