active: "dev"

prod:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "mainnet"
  web: 
    push_server_url: "http://localhost:65522/api/push"
    port: 5000
    jwt_token: "SecureCosmostation!@#50291230728"

dev:
  node: 
    gaiad_url: "http://3.120.254.79:26657"
    lcd_url: "https://lcd-cosmos-free.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "test"
  web: 
    push_server_url: "http://localhost:65522/api/push"
    port: 5000
    jwt_token: "SecureCosmostation!@#50291230728"

testnet:
  node: 
    gaiad_url: "tcp://54.180.171.141:26657"
    lcd_url: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"
  web: 
    push_server_url: "http://localhost:65522/api/push"
    port: 5000
    jwt_token: "SecureCosmostation!@#50291230728"

