active: "prod"

prod:
  node: 
    gaiad_url: "http://13.209.139.204:26657"
    lcd_url: "https://lcd.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-2"
  raven:
    dsn: "https://02db34c9482641eba0f7d28c6f1c2607:26977dd6d1cb45ef95c2e2b1466f4d8a@sentry.io/1360655"
    address: "063286B58F0D01406B188796820C2DC895B21063"
    period: "10"

dev:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd-mainnet-dev.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "dev"
  raven:
    dsn: "https://02db34c9482641eba0f7d28c6f1c2607:26977dd6d1cb45ef95c2e2b1466f4d8a@sentry.io/1360655"
    address: "063286B58F0D01406B188796820C2DC895B21063"
    period: "10"

testnet:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd-gaia.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "gaia-13001"
  raven:
    dsn: "https://02db34c9482641eba0f7d28c6f1c2607:26977dd6d1cb45ef95c2e2b1466f4d8a@sentry.io/1360655"
    address: "063286B58F0D01406B188796820C2DC895B21063"
    period: "10"

keybase_url: "https://keybase.io/_/api/1.0/user/lookup.json?fields=pictures&key_suffix="