active: "mainnet"

mainnet:
  node: 
    rpc_node: "http://13.209.59.177:26657" # seoul sentry node
    lcd_endpoint: "https://lcd-cosmos.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-3-1"
  alarm:
    push_server_endpoint: "http://localhost:65522/api/push"
    switch: true # purpose is to stop sending push notification in case of syncing from the scratch 

dev:
  node: 
    rpc_node: "http://13.209.59.177:26657"
    lcd_endpoint: "https://lcd-cosmos.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-dev"
  alarm:
    push_server_endpoint: "http://localhost:65522/api/push"
    switch: false # purpose is to stop sending push notification in case of syncing from the scratch 

testnet:
  node: 
    rpc_node: "http://54.180.171.141:26657" # seoul testnet node
    lcd_endpoint: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"
  alarm:
    push_server_endpoint: "http://localhost:65522/api/push"
    switch: false # purpose is to stop sending push notification in case of syncing from the scratch 

keybase_endpoint: "https://keybase.io/_/api/1.0/user/lookup.json?fields=pictures&key_suffix="