network_type: "dev"

mainnet:
  node: 
    rpc_node: "http://13.209.59.177:26657"
    lcd_endpoint: "https://lcd-cosmos.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-3-1"
  market:
    coingecko_endpoint: "https://api.coingecko.com/api/v3"

dev:
  node: 
    rpc_node: "http://13.209.59.177:26657"
    lcd_endpoint: "https://lcd-cosmos.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-dev-mig"
  market:
    coingecko_endpoint: "https://api.coingecko.com/api/v3"

testnet:
  node: 
    rpc_node: "http://54.180.171.141:26657"
    lcd_endpoint: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"
  market:
    coingecko_endpoint: "https://api.coingecko.com/api/v3"
    