active: "prod"

prod:
  node: 
    gaiad_url: "http://13.209.139.204:26657"
    lcd_url: "https://lcd.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-3"

dev:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd-mainnet-dev.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "dev-test"

testnet:
  node: 
    gaiad_url: "http://54.180.171.141:26657"
    lcd_url: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"

market:
  coinmarketcap: 
    url: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
    coin_id: "3794"
    api_key: "1a9784e7-e592-449c-a123-744583ec25e8"
  coingecko:
    url: "https://api.coingecko.com/api/v3/coins/cosmos"
    