active: "mainnet"

mainnet:
  node: 
    rpc_node: "http://13.124.168.183:26657"
    lcd_endpoint: "https://lcd-cosmos.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-3-1"
  web:
    port: 5000

dev:
  node: 
    rpc_node: "http://52.78.163.36:26657"
    lcd_endpoint: "https://lcd-mainnet-dev.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmoshub-3-dev"
  web:
    port: 5000

testnet:
  node: 
    rpc_node: "http://54.180.171.141:26657"
    lcd_endpoint: "https://lcd-cosmos-testnet.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-testnet"
  web:
    port: 5000
  
market:  
  coingecko:
    endpoint: "https://api.coingecko.com/api/v3/coins/cosmos"  
  coinmarketcap: 
    endpoint: "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"
    coin_id: "3794"
    api_key: "1a9784e7-e592-449c-a123-744583ec25e8"
