active: "dev"

prod:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "mainnet"
  port: 5000
  jwt: 
    token: "SecureCosmostation!@#50291230728"

dev:
  node: 
    gaiad_url: "http://52.78.163.36:26657"
    lcd_url: "https://lcd-mainnet-dev.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com:5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "dev-test"
  port: 5000
  jwt:
    token: "SecureCosmostation!@#50291230728"