active: "dev"

mainnet:
  node: 
    chain_id: "cosmoshub-3"
    rpc_node: "http://13.124.168.183:26657"
    lcd_endpoint: "https://lcd-cosmos-app.cosmostation.io"
  database:
    host: "cosmostation.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "CosmosGo00!!"
    table: "cosmoshub-3-1"

dev:
  node: 
    rpc_node: "http://54.180.171.141:26657"
    lcd_endpoint: "https://lcd-cosmos-app.cosmostation.io"
  database:
    host: "cosmostation-dev.ci6bhjszmrb3.ap-northeast-2.rds.amazonaws.com"
    port: "5432"
    user: "root"
    password: "dnpfqldwhr00!!"
    table: "cosmos-dev"