package types

const (
	PrefixAuth = "/cosmos/auth/v1beta1"
	// auth_account_address = "/accounts/{address}"
	// auth_params          = "/params"

	PrefixBank = "/cosmos/bank/v1beta1"
	// bank_balance_address        = "/balances/{address}"
	// bank_balances_address_denom = "/balances/{address}/{denom}"
	// bank_params                 = "/params"
	// bank_supply                 = "/supply"
	// bank_supply_denom           = "/supply/{denom}"

	PrefixDistribution = "/cosmos/distribution/v1beta1"
	// distribution_communitypool                                        = "/community_pool"
	// distribution_delegatros_delegatoraddress_rewards                  = "/delegators/{delegator_address}/rewards"
	// distribution_delegators_delegatoraddress_rewards_validatoraddress = "/delegators/{delegator_address}/rewards/{validator_address}"
	// distribution_delegators_delegatoraddress_validators               = "/delegators/{delegator_address}/validators"
	// distribution_delegators_delegatoraddress_withdrawaddress          = "/delegators/{delegator_address}/withdraw_address"
	// distribution_params                                               = "/params"
	// distribution_validators_validatoraddress_commission               = "/validators/{validator_address}/commission"
	// distribution_validators_validatoraddress_outstandingrewards       = "/validators/{validator_address}/outstanding_rewards"
	// distribution_validators_validatoraddress_slashes                  = "/validators/{validator_address}/slashes"

	PrefixEvidence = "/cosmos/evidence/v1beta1"
	// evidence_evidence              = "/evidence"
	// evidence_evidence_evidencehash = "/evidence/{evidence_hash}"

	PrefixGov = "/cosmos/gov/v1beta1"
	// gov_params_paramstype                       = "/params/{params_type}"
	// gov_proposals                               = "/proposals"
	// gov_proposals_proposalid                    = "/proposals/{proposal_id}"
	// gov_proposals_proposal_id_deposits          = "/proposals/{proposal_id}/deposits"
	// gov_proposals_proposalid_deposits_depositor = "/proposals/{proposal_id}/deposits/{depositor}"
	// gov_proposals_proposalid_tally              = "/proposals/{proposal_id}/tally"
	// gov_proposals_proposalid_votes              = "/proposals/{proposal_id}/votes"
	// gov_proposals_proposalid_votes_voter        = "/proposals/{proposal_id}/votes/{voter}"

	PrefixMint = "/cosmos/mint/v1beta1"
	// mint_annual_provisions = "/annual_provisions"
	// mint_inflation         = "/inflation"
	// mint_params            = "/params"

	PrefixParams = "/cosmos/params/v1beta1"
	// params_params = "/params"

	PrefixSlashing = "/cosmos/slashing/v1beta1"
	// slashing_params                    = "/params"
	// slashing_signing_infos             = "/signing_infos"
	// slashing_signing_infos_consaddress = "/signing_infos/{cons_address}"

	PrefixStaking = "/cosmos/staking/v1beta1"
	// staking_delegations_delegatoraddr                                             = "/delegations/{delegator_addr}"
	// staking_delegators_delegatoraddr_redelegations                                = "/delegators/{delegator_addr}/redelegations"
	// staking_delegators_delegatoraddr_unbondingdelegations                         = "/delegators/{delegator_addr}/unbonding_delegations"
	// staking_delegators_delegatoraddr_validators                                   = "/delegators/{delegator_addr}/validators"
	// staking_delegators_delegatoraddr_validators_validatoraddr                     = "/delegators/{delegator_addr}/validators/{validator_addr}"
	// staking_historicalinfo_height                                                 = "/historical_info/{height}"
	// staking_params                                                                = "/params"
	// staking_pool                                                                  = "/pool"
	// staking_validators                                                            = "/validators"
	// staking_validators_validatoraddr                                              = "/validators/{validator_addr}"
	// staking_validators_validatoraddr_delegations                                  = "/validators/{validator_addr}/delegations"
	// staking_validators_validatoraddr_delegations_delegatoraddr                    = "/validators/{validator_addr}/delegations/{delegator_addr}"
	// staking_validators_validatoraddr_delegations_delegatoraddr_unbodingdelegation = "/validators/{validator_addr}/delegations/{delegator_addr}/unbonding_delegation"
	// staking_validators_validatoraddr_unbondingdelegations                         = "/validators/{validator_addr}/unbonding_delegations"

	PrefixUpgrade = "/cosmos/upgrade/v1beta1"
	// upgrade_appliedplan_name = "/applied_plan/{name}"
	// // upgrade_currentplan      = "/current_plan"

	PrefixIBCChannel = "/ibc/channel/v1beta1"
	// ibc_channel_channels                                                                                       = "/channels"
	// ibc_channel_channels_channelid_ports_portid                                                                = "/channels/{channel_id}/ports/{port_id}"
	// ibc_channel_channels_channelid_ports_portid_clientstate                                                    = "/channels/{channel_id}/ports/{port_id}/client_state"
	// ibc_channel_channels_channelid_ports_portid_consensusstate_version_version_number_height_version_height    = "/channels/{channel_id}/ports/{port_id}/consensus_state/version/{version_number}/height/{version_height}"
	// ibc_channel_channels_channelid_ports_portid_nextsequence                                                   = "/channels/{channel_id}/ports/{port_id}/next_sequence"
	// ibc_channel_channels_channelid_ports_portid_packetacks_sequence                                            = "/channels/{channel_id}/ports/{port_id}/packet_acks/{sequence}"
	// ibc_channel_channels_channelid_ports_portid_packet_commitments                                             = "/channels/{channel_id}/ports/{port_id}/packet_commitments"
	// ibc_channel_channels_channelid_ports_portid_packet_commitments_packetcommitmentsequences_unreceivedpackets = "/channels/{channel_id}/ports/{port_id}/packet_commitments/{packet_commitment_sequences}/unreceived_packets"
	// ibc_channel_channels_channelid_ports_portid_packet_commitments_packetcommitmentsequences_unrelayedacks     = "/channels/{channel_id}/ports/{port_id}/packet_commitments/{packet_commitment_sequences}/unrelayed_acks"
	// ibc_channel_channels_channelid_ports_portid_packet_commitments_sequence                                    = "/channels/{channel_id}/ports/{port_id}/packet_commitments/{sequence}"
	// ibc_channel_connections_connection_channels                                                                = "/connections/{connection}/channels"

	PrefixIBCClient = "/ibc/client/v1beta1"
	// ibc_client_clientstates                                                        = "/client_states"
	// ibc_client_clientstates_clientid                                               = "/client_states/{client_id}"
	// ibc_client_consensusstates_clientid                                            = "/consensus_states/{client_id}"
	// ibc_client_consensusstates_clientid_version_versionnumber_height_versionheight = "/consensus_states/{client_id}/version/{version_number}/height/{version_height}"

	PrefixIBCConnection = "/ibc/connection/v1beta1"
	// ibc_connection_clientconnections_clientid                                                         = "/client_connections/{client_id}"
	// ibc_connection_connections                                                                        = "/connections"
	// ibc_connection_connections_connectionid                                                           = "/connections/{connection_id}"
	// ibc_connection_connections_connectionid_clientstate                                               = "/connections/{connection_id}/client_state"
	// ibc_connection_connections_connectionid_consensusstate_version_versionnumber_height_versionheight = "/connections/{connection_id}/consensus_state/version/{version_number}/height/{version_height}"

	PrefixIBCTransfer = "/ibc_transfer/v1beta1"
	// ibctransfer_denom_traces      = "/denom_traces"
	// ibctransfer_denom_traces_hash = "/denom_traces/{hash}"
	// ibctransfer_params            = "/params"
)
